const quotes = [
  { content: "心存温柔，山河浪漫。", theme: "life", author: null },
  { content: "慢慢来，好戏都在烟火里。", theme: "life", author: null },
  { content: "你是我疲惫生活里的英雄梦想。", theme: "love", author: null },
  { content: "今天的不开心就到此为止。", theme: "life", author: null },
  { content: "爱自己是终身浪漫的开始。", theme: "life", author: "王尔德" },
  { content: "万物皆有裂痕，那是光照进来的地方。", theme: "life", author: "莱昂纳德·科恩" },
  { content: "唯有你也想见我的时候，我们见面才有意义。", theme: "love", author: "西蒙·波娃" },
  { content: "月亮不会奔你而来，星星也不会。", theme: "growth", author: null },
  { content: "保持热爱，奔赴山海。", theme: "life", author: null },
  { content: "你的可爱，治愈一切不可爱。", theme: "love", author: null },
  { content: "眼里是阳光，笑里是坦荡。", theme: "life", author: null },
  { content: "先成为自己的光，再温暖身边的人。", theme: "growth", author: null },
  { content: "简单地喜欢，温暖地陪伴。", theme: "love", author: null },
  { content: "生活原本沉闷，但跑起来就有风。", theme: "life", author: null },
  { content: "时间从来不语，却回答了所有问题。", theme: "growth", author: null },
  { content: "你是独特且值得被爱的。", theme: "love", author: null },
  { content: "所有的美好都在路上。", theme: "life", author: null },
  { content: "带着微笑，去追赶明天。", theme: "life", author: null },
  { content: "温柔半两，从容一生。", theme: "life", author: null },
  { content: "来日方长，何惧路遥马慢。", theme: "growth", author: null },
  { content: "一路向阳，温暖前行。", theme: "life", author: null },
  { content: "你嘴角上扬的样子真好看。", theme: "love", author: null },
  { content: "山野千里，你是我藏在微风里的欢喜。", theme: "love", author: null },
  { content: "日落尤其温柔，人间皆是浪漫。", theme: "life", author: null },
  { content: "在心里种花，人生才不会荒芜。", theme: "growth", author: null },
  { content: "风已经是秋天的味道了。", theme: "life", author: null },
  { content: "你要做自己人生的小太阳。", theme: "growth", author: null },
  { content: "在喜欢你的人那里去热爱生活。", theme: "love", author: null },
  { content: "永远善良，永远来日方长。", theme: "life", author: null },
  { content: "比起过往，前方更值得期待。", theme: "growth", author: null },
  { content: "有人爱，有事做，有所期待。", theme: "life", author: null },
  { content: "你逆光而来，配得上这世间所有的好。", theme: "love", author: null },
  { content: "保持纯真，保持勇敢。", theme: "growth", author: null },
  { content: "慢品人间烟火色，闲观万事岁月长。", theme: "life", author: null },
  { content: "我想在山谷里开一家店，贩卖黄昏的温柔。", theme: "life", author: null },
  { content: "让喜欢的事情成为生活的常态。", theme: "life", author: null },
  { content: "有你在的地方就是最好的风景。", theme: "love", author: null },
  { content: "向前看，阳光依然灿烂。", theme: "growth", author: null },
  { content: "把日子过成诗，简单而精致。", theme: "life", author: null },
  { content: "愿你眼里长着太阳，笑里全是坦荡。", theme: "life", author: null },
  { content: "人间值得，夜色温柔。", theme: "life", author: null },
  { content: "错过了落日余晖，还会有满天星辰。", theme: "growth", author: null },
  { content: "星河长明，幸运不止。", theme: "life", author: null },
  { content: "你一来，便是晴天。", theme: "love", author: null },
  { content: "满怀希望就会所向披靡。", theme: "growth", author: null },
  { content: "与其互为人间，不如自成宇宙。", theme: "growth", author: null },
  { content: "即使平凡的日子也要泛着光。", theme: "life", author: null },
  { content: "春风十里，不及相遇有你。", theme: "love", author: null },
  { content: "晴空万里，不及心中有你。", theme: "love", author: null },
  { content: "出发，到新的爱与喧嚣中去。", theme: "growth", author: null },
  { content: "在不安的世界里独善其身。", theme: "growth", author: null },
  { content: "你眼中的星河，是我从没见过的人间。", theme: "love", author: null },
  { content: "此生如鸿，唯你不负。", theme: "love", author: null },
  { content: "把开心碾碎了揉进日子里。", theme: "life", author: null },
  { content: "日子渺小重复，却都是幸福。", theme: "life", author: null },
  { content: "愿你足够强大，无需他人照亮。", theme: "growth", author: null },
  { content: "内心温柔，步步生花。", theme: "life", author: null },
  { content: "对生活中的每一件小事心怀感恩。", theme: "life", author: null },
  { content: "与你在一起的每一天都是纪念日。", theme: "love", author: null },
  { content: "无忧无虑，百事从欢。", theme: "life", author: null },
  { content: "星光不问赶路人，时光不负有心人。", theme: "growth", author: null },
  { content: "小小日子，悠哉悠哉。", theme: "life", author: null },
  { content: "最好的时光在路上。", theme: "life", author: null },
  { content: "愿你笑靥如花，一生不减芳华。", theme: "life", author: null },
  { content: "喜欢是乍见之欢，爱是久处不厌。", theme: "love", author: null },
  { content: "我喜欢你，山海为证。", theme: "love", author: null },
  { content: "心愿是陪你从日出到日落。", theme: "love", author: null },
  { content: "阳光很暖，微风很甜，你很好看。", theme: "love", author: null },
  { content: "一生太短，一瞬好长。", theme: "life", author: null },
  { content: "烟火向星辰，所愿皆成真。", theme: "life", author: null },
  { content: "保持可爱，不要焦虑。", theme: "life", author: null },
  { content: "好事发生，就在下一个转弯。", theme: "growth", author: null },
  { content: "最好的总在不经意间出现。", theme: "life", author: null },
  { content: "一万年太久，只争朝夕。", theme: "growth", author: null },
  { content: "美好的事物需要等待。", theme: "growth", author: null },
  { content: "山不见我，我自去见山。", theme: "growth", author: null },
  { content: "今天也是被温柔治愈的一天。", theme: "life", author: null },
  { content: "平安喜乐，万事顺遂。", theme: "life", author: null },
  { content: "闲看花开，静待花落。", theme: "life", author: null },
  { content: "愿所有美好都能如约而至。", theme: "life", author: null },
  { content: "温柔是宝藏，你也是。", theme: "love", author: null },
  { content: "无论何时，记得甜甜的笑。", theme: "life", author: null },
  { content: "一半烟火，一半诗意。", theme: "life", author: null },
  { content: "生活明朗，万物可爱。", theme: "life", author: null },
  { content: "珍惜所有的不期而遇。", theme: "life", author: null },
  { content: "念念不忘，必有回响。", theme: "growth", author: null },
  { content: "你若安好便是晴天。", theme: "love", author: null },
  { content: "世间美好与你环环相扣。", theme: "love", author: null },
  { content: "愿你活成自己喜欢的模样。", theme: "growth", author: null },
  { content: "把平凡的日子过得闪闪发光。", theme: "life", author: null },
  { content: "温柔坚定，勇敢向前。", theme: "growth", author: null },
  { content: "一步一个脚印地走向远方。", theme: "growth", author: null },
  { content: "在细碎的日常里收集快乐。", theme: "life", author: null },
  { content: "以欢喜之心，慢度日常。", theme: "life", author: null },
  { content: "愿你有烈酒也有清茶。", theme: "life", author: null },
  { content: "你可以无忧无虑地做自己。", theme: "life", author: null },
  { content: "做一朵向日葵，面向太阳，坦然生长。", theme: "growth", author: null },
  { content: "记得天涯海角，总会有人愿意拥抱你。", theme: "life", author: null },
  { content: "愿你经历山河仍觉得人间值得。", theme: "growth", author: null },
  { content: "不论今天多不开心，明天都是崭新的一天。", theme: "life", author: null },
  { content: "走吧，我们去寻找喜欢的自己。", theme: "growth", author: null },
];

function getDayIndex(): number {
  const now = new Date();
  const dayOfYear = Math.floor(
    (now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return dayOfYear % quotes.length;
}

export function getDailyQuote() {
  return quotes[getDayIndex()];
}

export function getQuoteCount() {
  return quotes.length;
}