name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm install
      - name: Push database schema (prisma db push)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db push --accept-data-loss
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build
        run: npx next build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          QWEATHER_KEY: ${{ secrets.QWEATHER_KEY }}
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Deploy
        run: vercel . --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --env DATABASE_URL="${{ secrets.DATABASE_URL }}" --env DEEPSEEK_API_KEY="${{ secrets.DEEPSEEK_API_KEY }}" --env QWEATHER_KEY="${{ secrets.QWEATHER_KEY }}"
